robot_config:
  tcp_link_name: "right_gripper"    # defines the pose of the tool center point
  base_link_name: "panda_link0"
  eef_links: ["panda_link8", "panda_hand", "panda_grasptarget", "right_gripper", "panda_leftfinger", "panda_rightfinger"] # links belonging to the end effector
  auxiliary_joint_names: ["panda_finger_joint1", "panda_finger_joint2"]  # joints not controlled by neural network
  auxiliary_joints_values: [0.04, 0.04]  # default values of auxiliary joints
  neutral_config: [-0.017792060227770554, -0.7601235411041661, 0.019782607023391807, -2.342050140544315, 0.029840531355804868, 1.5411935298621688, 0.7534486589746342] # in order of how non-auxiliary joints are defined in urdf