version: '3.8'

services:
  avoid-everything-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: fishbotics
    image: avoid-everything:latest
    
    # GPU access (equivalent to --gpus all)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Network and privilege settings
    network_mode: host
    privileged: true
    
    # Environment variables
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,compute,utility
      - NCCL_DEBUG=WARN
      - PYTHONPATH=/workspace
    
    # Volume mounts
    volumes:
      # Mount the workspace (parent directory which contains the whole repo)
      - ..:/workspace:cached
      # Mount X11 socket for GUI applications
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Mount host's timezone
      - /etc/localtime:/etc/localtime:ro
    
    # Working directory
    working_dir: /workspace
    
    # Keep container running
    stdin_open: true
    tty: true
    
    # Command to run
    command: /bin/bash -c "while sleep 1000; do :; done" 